name: Build & Deploy Test ReMe Wallet API
on:
  push:
    branches:
    - abv
env:
  DOCKER_REGISTRY: "eu.gcr.io/reme-wallet-test/"
  DOCKER_VERSION: 0.0.${GITHUB_RUN_NUMBER}
  DOCKER_NAME: reme-wallet-api-${GITHUB_REF##*/}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '281.0.0'
        project_id: reme-wallet-test
        service_account_key: ${{ secrets.GKE_TEST_KEY }}
    - run: |
        gcloud auth configure-docker

    - name: build docker image
      run: |
        docker build \
        --build-arg PORT=80 \
        --build-arg SIGN_UP_REWARD=${{ secrets.SIGN_UP_REWARD }} \
        --build-arg DB_CONNECTION=${{ secrets.DB_CONNECTION }} \
        --build-arg ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
        --build-arg ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
        --build-arg ADMIN_PRIVATE_KEY=${{ secrets.ADMIN_PRIVATE_KEY }} \
        --build-arg BLOCKCHAIN_NETWORK=${{ secrets.BLOCKCHAIN_NETWORK }} \
        --build-arg DISTRIBUTION_CONTRACT=${{ secrets.DISTRIBUTION_CONTRACT }} \
        -t reme-wallet-api .

    - name: set tags to docker images
      run: |
        docker tag reme-wallet-api ${{ env.DOCKER_REGISTRY }}${{ env.DOCKER_NAME }}:latest
        docker tag reme-wallet-api ${{ env.DOCKER_REGISTRY }}${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}
    
    - name: push docker images
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}${{ env.DOCKER_NAME }}:latest
        docker push ${{ env.DOCKER_REGISTRY }}${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}
    
    - name: logout docker
      run: docker logout
      
    - uses: actions-hub/gcloud@master
      name: deploy service
      env:
        PROJECT_ID:  reme-wallet-test
        APPLICATION_CREDENTIALS: ${{ secrets.GKE_TEST_KEY }}
      with:
        args: app deploy ./app-test.yaml --image-url=${{ env.DOCKER_REGISTRY }}${{ env.DOCKER_NAME }}:latest